# default-limitrange.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limitrange
  namespace: default
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "0.9"
    default:
      cpu: "0.9"
